### ISSUE TITLE
RSA Key Exchange condition

### ISSUE THREAD

**Issue by cplvic** [robotattackorg/robot-detect#11]
Great job on this! I have a comment, I tested offline testssl.sh and dev.ssllabs.com
Your publication on Page 4 calls out that RSA Key Exchange is problematic but your website doesn't.
As a result other tools not marking RSA Key exchange as a problem so for example, 
TLS_RSA_WITH_AES_128_CBC_SHA* is marked okay. 

Can you clarify? @hannob

**Comment by hannob** [comment]
Hi,

Not sure what you mean, we write on the webpage:

```
Disable RSA encryption!
ROBOT only affects TLS cipher modes that use RSA encryption. Most modern TLS connections use an Elliptic Curve Diffie Hellman key exchange and need RSA only for signatures. We believe RSA encryption modes are so risky that the only safe course of action is to disable them. Apart from being risky these modes also lack forward secrecy.

By disabling RSA encryption we mean all ciphers that start with TLS_RSA. It does not include the ciphers that use RSA signatures and include DHE or ECDHE in their name. These ciphers are not affected by our attack.
```

Isn't that very clear?

I can't influence what external tools do, but I guess the discussion whether TLS_RSA should be deprecated will take some time. I think it's been one of the more controversial claims of our paper.

**Comment by cplvic** [comment]
HI @hannob I full agree. I was simply asking because in some scans I see that RSA is used for **key exchange** but not encryption. Encryption uses AES.

I'm following your publication and I'm simply wondering if your page should align with your publication and also mention Key Exchange is suspect as well so admins do not get some false sense of security.

Thanks very much!
