### ISSUE TITLE
make it compatible with Python 2.7

### ISSUE THREAD

**Issue by j-ed** [robotattackorg/robot-detect#13]
Hi @hannob I like to run your program on one of my servers which has Python 2.7 installed by default.
Now I wonder if it would be possible to make it compatible with this version. I already did some tests on my own but without success (I'm not a Python expert). The following error is shown if I execute it:
```
...
RSA e: 0x10001
Modulus size: 2048 bits, 256 bytes
Traceback (most recent call last):
  File "./robot-detect", line 184, in <module>
    pms_good = int(gmpy2.powmod(pms_good_in, e, N)).to_bytes(modulus_bytes, byteorder="big")
AttributeError: 'long' object has no attribute 'to_bytes'
```
From what I understood a `to_bytes` attribute doesn't exist for that version, but people seem to have discussed this kind of problem already and provided possible workarounds: https://github.com/therealmik/pyrdiff/issues/1

**Comment by hannob** [comment]
I have no interest in making the code less readable to make it compatible with outdated python versions, sorry. You don't have to run the code on the server you're testing.
