### ISSUE TITLE
SNI?

### ISSUE THREAD

**Issue by wotschel** [robotattackorg/robot-detect#14]
Hi,

does this script support SNI? (I assume that it doesn't support SNI.) It seems to me that it is always scanning  the "default" VHOST on an apache-webserver. 

Thanks and Best Regards!

**Comment by hannob** [comment]
No, it doesn't. It's a deliberate choice, it would be quite complex to add it.
We decided it's not worth it, as we assume servers that are vulnerable depending on the SNI config are relatively rare. testssl.sh supports SNI, use that.
