### ISSUE TITLE
Support connections with certificates

### ISSUE THREAD

**Issue by M1ckael4** [robotattackorg/robot-detect#15]
Hello,

Can not verify web sites that require a client certificate : 

Cannot connect to server: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:777)

is it possible to add an option to indicate the path of the certificate to use ? 

Thank you

**Comment by hannob** [comment]
No, it would be incredibly complicated to add clientcert support (we basically implement primitive TLS on our own and would have to change a lot) and given the low incidence of clientcert usage not worth it.
