### ISSUE TITLE
Import Error: No module named gmpy2

### ISSUE THREAD

**Issue by 007divyachawla** [robotattackorg/robot-detect#3]
On running the following command python robot-detect it is giving the following error.

![image](https://user-images.githubusercontent.com/7563150/33904295-006eba38-df30-11e7-8820-b5389e6e4263.png)

Please provide the solution

**Comment by devsecur** [comment]
You have to install gmpy2. An installation guide is published on https://gmpy2.readthedocs.io/en/latest/

**Comment by hannob** [comment]
not a bug, gmpy2 is a dependency
