### ISSUE TITLE
Sites without SSLv3 are not able to be checked

### ISSUE THREAD

**Issue by BlackDex** [robotattackorg/robot-detect#7]
I Don't know if this is good or not, but sites which do not have SSLv3 enabled are generating an error as shown below:

Scanning host www.ssllabs.com ip 64.41.200.100 port 443
Cannot connect to server: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:645)

Does this mean the site is not vulnerable? If so, then i think it would be nice that this error is catched and reported to be secure.

**Comment by hannob** [comment]
The problem is not that this doesn't speak SSLv3, the problem is it's not supporting RSA. (Which actually is kinda ideal). I should improve the output.

**Comment by BlackDex** [comment]
Ah, ok. Good to know, figured that, but wasn't sure.
Thx

**Comment by hannob** [comment]
I think this should be resolved with
https://github.com/robotattackorg/robot-detect/commit/5b49bc75d8449944b84aacc835aaf5e3e283830e
