### ISSUE TITLE
Also requires python3 cryptography module

### ISSUE THREAD

**Issue by daemondazz** [robotattackorg/robot-detect#8]
README should be updated as I also had to install python3-cryptography (on Ubuntu 16.04) due to x509 import.

**Comment by draeath** [comment]
It would be best if a `requirements.txt` was added to the repo, perhaps.

**Comment by klikevil** [comment]
pip3 install --upgrade pip; pip3 install --upgrade x509 cryptography

worked for me.

**Comment by draeath** [comment]
Didn't even need x509 (dependency).

**Comment by daemondazz** [comment]
x509 is part of the cryptography library, so you don't need it install it separately.
